In [8]:
import pandas as pd
import numpy as np
data = pd.read_csv("weatherAUS.csv")
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,0.0,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0.0,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,1.4,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,0.0,No
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,No,2.2,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes,15.6,Yes
12,2008-12-13,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes,3.6,Yes
13,2008-12-14,Albury,12.6,21.0,3.6,NaN,NaN,SW,44.0,W,...,43.0,1001.2,1001.8,NaN,7.0,15.8,19.8,Yes,0.0,No
14,2008-12-15,Albury,8.4,24.6,0.0,NaN,NaN,NaN,NaN,S,...,32.0,1009.7,1008.7,NaN,NaN,15.9,23.5,No,NaN,NaN
15,2008-12-16,Albury,9.8,27.7,NaN,NaN,NaN,WNW,50.0,NaN,...,28.0,1013.4,1010.3,0.0,NaN,17.3,26.2,NaN,0.0,No
16,2008-12-17,Albury,14.1,20.9,0.0,NaN,NaN,ENE,22.0,SSW,...,82.0,1012.2,1010.4,8.0,1.0,17.2,18.1,No,16.8,Yes
17,2008-12-18,Albury,13.5,22.9,16.8,NaN,NaN,W,63.0,N,...,65.0,1005.8,1002.2,8.0,1.0,18.0,21.5,Yes,10.6,Yes
18,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,WSW,...,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,Yes,0.0,No
19,2008-12-20,Albury,9.8,25.6,0.0,NaN,NaN,SSE,26.0,SE,...,26.0,1019.2,1017.1,NaN,NaN,15.8,23.2,No,0.0,No
20,2008-12-21,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No,0.0,No
21,2008-12-22,Albury,17.1,33.0,0.0,NaN,NaN,NE,43.0,NE,...,28.0,1013.6,1008.1,NaN,1.0,24.5,31.6,No,0.0,No
22,2008-12-23,Albury,20.5,31.8,0.0,NaN,NaN,WNW,41.0,W,...,24.0,1007.8,1005.7,NaN,NaN,23.8,30.8,No,0.0,No
23,2008-12-24,Albury,15.3,30.9,0.0,NaN,NaN,N,33.0,ESE,...,23.0,1011.0,1008.2,5.0,NaN,20.9,29.0,No,0.0,No
24,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,E,...,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No,0.0,No
25,2008-12-26,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No,0.0,No
26,2008-12-27,Albury,16.9,33.0,0.0,NaN,NaN,WSW,57.0,NaN,...,28.0,1006.8,1003.6,NaN,1.0,26.6,31.2,No,0.0,No
27,2008-12-28,Albury,20.1,32.7,0.0,NaN,NaN,WNW,48.0,N,...,15.0,1005.2,1001.7,NaN,NaN,24.6,32.1,No,0.0,No
28,2008-12-29,Albury,19.7,27.2,0.0,NaN,NaN,WNW,46.0,NW,...,22.0,1004.8,1004.2,NaN,NaN,21.6,26.1,No,1.2,Yes
29,2008-12-30,Albury,12.5,24.2,1.2,NaN,NaN,WNW,50.0,WSW,...,70.0,1005.6,1003.4,8.0,8.0,12.5,18.2,Yes,0.8,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145430,2017-05-27,Uluru,9.3,28.0,0.0,NaN,NaN,W,28.0,SSW,...,16.0,1019.9,1016.9,NaN,NaN,16.6,27.3,No,0.0,No
145431,2017-05-28,Uluru,8.0,24.6,0.0,NaN,NaN,E,33.0,SE,...,25.0,1021.7,1018.8,4.0,NaN,13.8,23.5,No,0.0,No
145432,2017-05-29,Uluru,12.7,22.2,0.0,NaN,NaN,E,37.0,E,...,34.0,1024.3,1021.7,8.0,8.0,13.9,21.0,No,0.0,No
145433,2017-05-30,Uluru,9.4,22.7,0.0,NaN,NaN,E,35.0,SE,...,32.0,1026.6,1023.6,8.0,4.0,11.8,22.3,No,0.0,No
145434,2017-05-31,Uluru,5.4,20.5,0.0,NaN,NaN,E,46.0,E,...,32.0,1029.2,1025.3,NaN,NaN,11.1,20.2,No,0.0,No
145435,2017-06-01,Uluru,5.6,19.4,0.0,NaN,NaN,E,43.0,E,...,22.0,1029.6,1027.1,NaN,NaN,9.7,18.3,No,0.0,No
145436,2017-06-02,Uluru,1.5,19.2,0.0,NaN,NaN,E,37.0,ESE,...,18.0,1030.7,1026.7,NaN,NaN,6.8,17.6,No,0.0,No
145437,2017-06-03,Uluru,3.8,19.8,0.0,NaN,NaN,ENE,39.0,ESE,...,22.0,1028.7,1024.1,NaN,NaN,8.6,18.9,No,0.0,No
145438,2017-06-04,Uluru,4.5,18.8,0.0,NaN,NaN,E,31.0,ESE,...,26.0,1026.9,1022.4,NaN,NaN,9.5,18.6,No,0.0,No
145439,2017-06-05,Uluru,4.9,20.7,0.0,NaN,NaN,E,37.0,ESE,...,11.0,1027.1,1023.9,NaN,NaN,10.3,19.8,No,0.0,No
145440,2017-06-06,Uluru,1.2,20.8,0.0,NaN,NaN,E,43.0,ESE,...,6.0,1029.8,1025.9,NaN,NaN,7.9,19.9,No,0.0,No
145441,2017-06-07,Uluru,0.5,21.7,0.0,NaN,NaN,E,43.0,ESE,...,19.0,1029.0,1025.0,NaN,NaN,9.5,20.5,No,0.0,No
145442,2017-06-08,Uluru,4.0,20.0,0.0,NaN,NaN,SE,39.0,ESE,...,26.0,1030.2,1026.7,NaN,NaN,9.1,19.0,No,0.0,No
145443,2017-06-09,Uluru,3.4,19.8,0.0,NaN,NaN,E,43.0,ESE,...,23.0,1031.8,1027.7,NaN,NaN,8.7,18.9,No,0.0,No
145444,2017-06-10,Uluru,3.2,18.6,0.0,NaN,NaN,E,46.0,ESE,...,29.0,1031.0,1027.2,NaN,NaN,8.2,17.4,No,0.0,No
145445,2017-06-11,Uluru,2.4,19.1,0.0,NaN,NaN,E,33.0,SE,...,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,No,0.0,No
145446,2017-06-12,Uluru,5.1,19.7,0.0,NaN,NaN,E,46.0,ESE,...,29.0,1028.5,1025.8,NaN,NaN,8.5,19.2,No,0.0,No
145447,2017-06-13,Uluru,2.5,21.2,0.0,NaN,NaN,ENE,35.0,ESE,...,32.0,1027.2,1023.0,NaN,NaN,10.3,20.3,No,0.0,No
145448,2017-06-14,Uluru,2.3,21.4,0.0,NaN,NaN,SE,22.0,SE,...,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,No,0.0,No
145449,2017-06-15,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No,0.0,No
145450,2017-06-16,Uluru,5.2,24.3,0.0,NaN,NaN,E,24.0,SE,...,24.0,1023.8,1020.0,NaN,NaN,12.3,23.3,No,0.0,No
145451,2017-06-17,Uluru,6.4,23.4,0.0,NaN,NaN,ESE,31.0,S,...,25.0,1025.8,1023.0,NaN,NaN,11.2,23.1,No,0.0,No
145452,2017-06-18,Uluru,8.0,20.7,0.0,NaN,NaN,ESE,41.0,SE,...,32.0,1028.1,1024.3,NaN,7.0,11.6,20.0,No,0.0,No
145453,2017-06-19,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No,0.0,No
145454,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,0.0,No
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0.0,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0.0,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0.0,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,0.0,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN,NaN

In [9]:
np.sum(data.isnull())

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RISK_MM           3267
RainTomorrow      3267
dtype: int64

In [10]:
from scipy import stats
data = data.drop(columns = ['Evaporation','Sunshine', 'Cloud9am', 'Cloud3pm'])

In [12]:
data.describe()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RISK_MM
count,143975.000000,144199.000000,142199.000000,135197.000000,143693.000000,142398.000000,142806.000000,140953.000000,130395.00000,130432.000000,143693.000000,141851.00000,142193.000000
mean,12.194034,23.221348,2.360918,40.035230,14.043426,18.662657,68.880831,51.539116,1017.64994,1015.255889,16.990631,21.68339,2.360682
std,6.398495,7.119049,8.478060,13.607062,8.915375,8.809800,19.029164,20.795902,7.10653,7.037414,6.488753,6.93665,8.477969
min,-8.500000,-4.800000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.50000,977.100000,-7.200000,-5.40000,0.000000
25%,7.600000,17.900000,0.000000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.90000,1010.400000,12.300000,16.60000,0.000000
50%,12.000000,22.600000,0.000000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.60000,1015.200000,16.700000,21.10000,0.000000
75%,16.900000,28.200000,0.800000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.40000,1020.000000,21.600000,26.40000,0.800000
max,33.900000,48.100000,371.000000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.00000,1039.600000,40.200000,46.70000,371.000000

In [13]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0.2,No

In [17]:
data['RainToday'].replace({'No':0, 'Yes':1}, inplace=True)
data['RainTomorrow'].replace({'No':0, 'Yes':1}, inplace=True)

In [18]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,0.0,0.0,0.0
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,0.0,0.0,0.0
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,0.0,0.0,0.0
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,0.0,1.0,0.0
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,0.0,0.2,0.0

In [19]:
data['Rainfall'] = data['Rainfall'].fillna((data['Rainfall'].mean))
data['WindGustDir'] = data['WindGustDir'].fillna((data['WindGustDir'].mean))
data['WindGustSpeed'] = data['WindGustSpeed'].fillna((data['WindGustSpeed'].mean))
data['WindDir9am'] = data['WindDir9am'].fillna((data['WindDir9am'].mean))
data['WindDir3pm'] = data['WindDir3pm'].fillna((data['WindDir3pm'].mean))
data['WindSpeed9am'] = data['WindSpeed9am'].fillna((data['WindSpeed9am'].mean))
data['WindSpeed3pm'] = data['WindSpeed3pm'].fillna((data['WindSpeed3pm'].mean))
data['Humidity9am'] = data['Humidity9am'].fillna((data['Humidity9am'].mean))
data['Humidity3pm'] = data['Humidity3pm'].fillna((data['Humidity3pm'].mean))
data['Pressure9am'] = data['Pressure9am'].fillna((data['Pressure9am'].mean))
data['Pressure3pm'] = data['Pressure3pm'].fillna((data['Pressure3pm'].mean))
data['Temp9am'] = data['Temp9am'].fillna((data['Temp9am'].mean))
data['Temp3pm'] = data['Temp3pm'].fillna((data['Temp3pm'].mean))
data['RainToday'] = data['RainToday'].fillna((data['RainToday'].mean))
data['RISK_MM'] = data['RISK_MM'].fillna((data['RISK_MM'].mean))
data['RainTomorrow'] = data['RainTomorrow'].fillna((data['RainTomorrow'].mean))
data['MinTemp'] = data['MinTemp'].fillna((data['MinTemp'].mean))
data['MaxTemp'] = data['MinTemp'].fillna((data['MinTemp'].mean))

In [33]:
np.sum(data.isnull())

MinTemp          0
MaxTemp          0
Rainfall         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [35]:
from scipy import stats
data1 = data.drop(columns = ['Date','Location', 'WindGustDir', 'WindDir9am','WindDir3pm'])
z = np.abs(stats.zscore(data1._get_numeric_data())) #ini biar ngitung, tanpa variabel country
print(z)
data2 = data1[(z < 3).all(axis=1)] #melihat ukuran data setelah dihilangkan outlier
print(data2.shape)

KeyError: "['Date' 'Location' 'WindGustDir' 'WindDir9am' 'WindDir3pm'] not found in axis"

In [28]:
from sklearn.preprocessing import normalize
datanorm = normalize(data, norm='l2') #default norm L2, other are L1 and max
datanorm = pd.DataFrame(xnorm)
datanorm.tail()

TypeError: float() argument must be a string or a number, not 'method'

In [ ]:
from sklearn.feature_selection import SelectKBest, chi2
selector = SelectKBest(chi2, k="all")
X_new =selector.transform(Xx)
scores =selector.scores_
scores