In [14]:
#Tugas 1 - Data Integration

import pandas as pd

In [15]:
ccfraud1 = pd.read_csv('creditcardfraud1.csv')
ccfraud2 = pd.read_csv('creditcardfraud2.csv')

ccf_merged = pd.merge(ccfraud1, ccfraud2, on = 'Time')
ccf_merged = pd.concat([ccfraud1, ccfraud2], sort=True)

ccf_merged.head()

,Amount,Class,Time,V1,V10,V11,V12,V13,V14,V15,...,V26,V27,V28,V3,V4,V5,V6,V7,V8,V9
0,NaN,NaN,0.0,-1.359807,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,...,NaN,NaN,NaN,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787
1,NaN,NaN,0.0,1.191857,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,...,NaN,NaN,NaN,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425
2,NaN,NaN,1.0,-1.358354,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,...,NaN,NaN,NaN,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654
3,NaN,NaN,1.0,-0.966272,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,...,NaN,NaN,NaN,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024
4,NaN,NaN,2.0,-1.158233,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,...,NaN,NaN,NaN,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739

In [16]:
#Exporting
ccf_merged.to_csv("ccf_merged.csv")